from datetime import date, datetime, time
from typing import Annotated
from uuid import UUID
from pydantic import BaseModel, Field

from app.models.court_slot import CourtSlotCreate
from app.models.shuttle import ShuttleUsage

_SKILL_LEVELS = ('LB', 'MB', 'HB', 'LI', 'MI', 'HI', 'A')


class Session(BaseModel):
    id: UUID
    venue_id: UUID
    date: date
    start_time: time
    end_time: time           # GENERATED by DB — always consistent with start_time + duration_hours
    duration_hours: float
    courts_booked: str
    num_courts: int
    min_skill_level: str
    max_skill_level: str
    pub_fee: float
    max_pax: int
    status: str              # internal | published | completed
    telegram_message_id: int | None = None
    paynow_player_id: UUID | None = None
    created_at: datetime


class SessionCreate(BaseModel):
    venue_id: UUID
    date: date
    start_time: time
    duration_hours: float = 2.0
    courts_booked: str
    num_courts: int = 1
    min_skill_level: str = "LI"
    max_skill_level: str = "MI"
    pub_fee: float
    max_pax: Annotated[int, Field(gt=0)] | None = None  # None → service sets num_courts × 6
    paynow_player_id: UUID | None = None
    court_slots: Annotated[list[CourtSlotCreate], Field(min_length=1)]


class SessionUpdate(BaseModel):
    date: date | None = None
    start_time: time | None = None
    duration_hours: float | None = None  # updating this recomputes DB end_time automatically
    courts_booked: str | None = None
    num_courts: int | None = None
    min_skill_level: str | None = None
    max_skill_level: str | None = None
    pub_fee: float | None = None
    max_pax: Annotated[int, Field(gt=0)] | None = None
    paynow_player_id: UUID | None = None
    telegram_message_id: int | None = None
    # Note: status is managed via dedicated /publish and /complete endpoints.
    # shuttles_used is recorded via the /complete endpoint with ShuttleUsageCreate, not here.


class SessionWithRoster(Session):
    roster: list["RosterEntry"] = []
    shuttle_usage: list[ShuttleUsage] = []
    active_count: int = 0
    waitlist_count: int = 0


# Forward reference resolved below
from app.models.roster import RosterEntry
SessionWithRoster.model_rebuild()
