from __future__ import annotations

from datetime import date as _date, datetime, time as _time
from typing import Annotated, Literal
from uuid import UUID
from pydantic import BaseModel, Field

from app.models.court_slot import CourtSlotCreate
from app.models.shuttle import ShuttleUsage

SkillLevelStr = Literal['LB', 'MB', 'HB', 'LI', 'MI', 'HI', 'A']


class Session(BaseModel):
    id: UUID
    venue_id: UUID
    date: _date
    start_time: _time
    end_time: _time          # GENERATED by DB — always consistent with start_time + duration_hours
    duration_hours: float
    courts_booked: str
    num_courts: int
    min_skill_level: str
    max_skill_level: str
    pub_fee: float
    max_pax: int
    status: str              # internal | published | completed | cancelled
    telegram_message_id: int | None = None
    paynow_player_id: UUID | None = None
    created_at: datetime
    cancellation_reason: str | None = None


class SessionCreate(BaseModel):
    venue_id: UUID
    date: _date
    start_time: _time
    duration_hours: float = 2.0
    courts_booked: str
    num_courts: int = 1
    min_skill_level: SkillLevelStr = "HB"
    max_skill_level: SkillLevelStr = "LI"
    pub_fee: float
    max_pax: Annotated[int, Field(gt=0)] | None = None  # None → service sets num_courts × 6
    paynow_player_id: UUID | None = None
    court_slots: Annotated[list[CourtSlotCreate], Field(min_length=1)]


class SessionUpdate(BaseModel):
    venue_id: UUID | None = None
    date: _date | None = None
    start_time: _time | None = None
    duration_hours: float | None = None  # updating this recomputes DB end_time automatically
    courts_booked: str | None = None
    num_courts: int | None = None
    min_skill_level: SkillLevelStr | None = None
    max_skill_level: SkillLevelStr | None = None
    pub_fee: float | None = None
    max_pax: Annotated[int, Field(gt=0)] | None = None
    paynow_player_id: UUID | None = None
    telegram_message_id: int | None = None
    # Note: status is managed via dedicated /publish and /complete endpoints.
    # shuttles_used is recorded via the /complete endpoint with ShuttleUsageCreate, not here.


class SessionWithRoster(Session):
    roster: list[RosterEntry] = []
    shuttle_usage: list[ShuttleUsage] = []
    active_count: int = 0
    waitlist_count: int = 0


class CancelRequest(BaseModel):
    reason: Annotated[str, Field(min_length=1)]


# Forward reference resolved below
from app.models.roster import RosterEntry
SessionWithRoster.model_rebuild()
