"""
E2E test: Complete session lifecycle — updated for schema v2.

Workflow:
  1. Admin creates a session (with court_slots, duration_hours, min/max skill)
  2. Session is published (bot mocked)
  3. Guest player added to roster
  4. Admin verifies payment
  5. Admin completes session (no shuttles)
  6. P&L fetched and verified

Mocking:
  - app.db.client._service_client: sequential mock consuming responses in call order
  - bot_runner action methods: AsyncMock to prevent background tasks consuming DB mock responses
  - require_admin: overridden to bypass JWT check
"""
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from fastapi.testclient import TestClient

_SESSION_ID = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
_VENUE_ID = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"
_ENTRY_ID = "cccccccc-cccc-cccc-cccc-cccccccccccc"
_BOOKER_ID = "dddddddd-dddd-dddd-dddd-dddddddddddd"
_COURT_SLOT_ID = "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"
_TS = "2025-01-01T10:00:00+00:00"

_SESSION_INTERNAL = {
    "id": _SESSION_ID,
    "venue_id": _VENUE_ID,
    "date": "2025-06-15",
    "start_time": "09:00:00",
    "end_time": "11:00:00",      # GENERATED by DB
    "duration_hours": 2.0,
    "courts_booked": "Court 1",
    "num_courts": 1,
    "min_skill_level": "HB",
    "max_skill_level": "LI",
    "pub_fee": 10.0,
    "max_pax": 12,
    "status": "internal",
    "telegram_message_id": None,
    "paynow_player_id": None,
    "created_at": _TS,
}

_SESSION_PUBLISHED = {**_SESSION_INTERNAL, "status": "published"}
_SESSION_COMPLETED = {**_SESSION_INTERNAL, "status": "completed"}

_ENTRY_UNPAID = {
    "id": _ENTRY_ID,
    "session_id": _SESSION_ID,
    "player_id": None,
    "guest_name": "Alice",
    "player_type": "guest",
    "payment_status": "unpaid",
    "is_waitlisted": False,
    "position": 1,
    "joined_at": _TS,
    "created_at": _TS,
}
_ENTRY_PAID = {**_ENTRY_UNPAID, "payment_status": "verified_paid"}

_VENUE_ROW = {
    "id": _VENUE_ID,
    "name": "Test Hall",
    "court_cost_per_hour": 15.0,
    "default_pub_fee": 10.0,
    "created_at": _TS,
}

_COURT_SLOT_ROW = {
    "id": _COURT_SLOT_ID,
    "session_id": _SESSION_ID,
    "court_label": "Court 1",
    "from_time": "09:00:00",
    "to_time": "11:00:00",
    "booker_player_id": _BOOKER_ID,
    "created_at": _TS,
}


def _session_with_roster():
    """Returns a fresh dict — pop() in get_by_id() mutates it, so never reuse."""
    return {
        **_SESSION_COMPLETED,
        "roster_entries": [dict(_ENTRY_PAID)],
        "shuttle_usage": [],
    }


def _make_mock_db():
    client = MagicMock()
    builder = MagicMock()
    for method in ("select", "insert", "update", "delete", "eq", "order", "limit", "maybe_single", "in_"):
        getattr(builder, method).return_value = builder
    client.table.return_value = builder
    client.rpc.return_value = builder   # RPC calls also chain to builder
    return client, builder


def test_complete_session_lifecycle():
    """Full E2E: create → publish → join (guest) → verify payment → complete → P&L."""
    from app.dependencies import require_admin
    from app.main import app

    mock_client, mock_builder = _make_mock_db()

    # Responses consumed in exact execute() call order across all service calls.
    mock_builder.execute.side_effect = [
        # ── create session (via RPC) ──────────────────────────────────────────
        MagicMock(data=_SESSION_INTERNAL),          # rpc.execute() → new session row
        MagicMock(data=[]),                          # players(is_internal) → no auto-roster
        # ── publish ──────────────────────────────────────────────────────────
        MagicMock(data=[{"status": "internal"}]),   # sessions.select("status")
        MagicMock(data=[_SESSION_PUBLISHED]),        # sessions.update(published)
        # ── add guest ────────────────────────────────────────────────────────
        MagicMock(data=[{"max_pax": 12}]),           # sessions.select("max_pax")
        MagicMock(data=[]),                          # roster_entries active count → 0
        MagicMock(data=[]),                          # roster_entries max position → none
        MagicMock(data=[_ENTRY_UNPAID]),             # roster_entries.insert
        # ── verify payment ─────────────────────────────────────────────
        MagicMock(data=[_ENTRY_PAID]),               # roster_entries.update(verified_paid)
        # ── complete session ─────────────────────────────────────────────────
        MagicMock(data=[{"status": "published"}]),  # sessions.select("status")
        MagicMock(data=[_SESSION_COMPLETED]),        # sessions.update(completed)
        MagicMock(data=[_session_with_roster()]),    # get_by_id (nested select)
        # ── P&L ──────────────────────────────────────────────────────────────
        MagicMock(data=[_session_with_roster()]),    # get_by_id
        MagicMock(data=[_VENUE_ROW]),                # venues.select
        MagicMock(data=[_COURT_SLOT_ROW]),           # court_slots.select
        MagicMock(data=[{"id": _BOOKER_ID, "name": "Belle"}]),  # booker names
        MagicMock(data=[]),                          # players(is_internal) for exclusion
    ]

    app.dependency_overrides[require_admin] = lambda: None

    try:
        with (
            patch("app.db.client._service_client", mock_client),
            patch("app.bot.runner.bot_runner.build"),
            patch("app.bot.runner.bot_runner.start_polling", new_callable=AsyncMock),
            patch("app.bot.runner.bot_runner.post_session_announcement", new_callable=AsyncMock),
            patch("app.bot.runner.bot_runner.edit_session_message", new_callable=AsyncMock),
            patch("app.bot.runner.bot_runner.update_payment_in_message", new_callable=AsyncMock),
        ):
            with TestClient(app) as client:
                headers = {"Authorization": "Bearer test-token"}

                # 1. Create session
                resp = client.post(
                    "/api/v1/sessions",
                    json={
                        "venue_id": _VENUE_ID,
                        "date": "2025-06-15",
                        "start_time": "09:00:00",
                        "duration_hours": 2.0,
                        "courts_booked": "Court 1",
                        "num_courts": 1,
                        "min_skill_level": "HB",
                        "max_skill_level": "LI",
                        "pub_fee": 10.0,
                        "max_pax": 12,
                        "court_slots": [
                            {
                                "court_label": "Court 1",
                                "from_time": "09:00:00",
                                "to_time": "11:00:00",
                                "booker_player_id": _BOOKER_ID,
                            }
                        ],
                    },
                    headers=headers,
                )
                assert resp.status_code == 201, resp.text
                assert resp.json()["status"] == "internal"

                # 2. Publish session
                resp = client.post(f"/api/v1/sessions/{_SESSION_ID}/publish", headers=headers)
                assert resp.status_code == 200, resp.text
                assert resp.json()["status"] == "published"

                # 3. Add a guest player
                resp = client.post(
                    f"/api/v1/sessions/{_SESSION_ID}/roster/guest",
                    json={"guest_name": "Alice"},
                    headers=headers,
                )
                assert resp.status_code == 201, resp.text
                assert resp.json()["guest_name"] == "Alice"
                assert resp.json()["payment_status"] == "unpaid"

                # 4. Verify payment
                resp = client.post(
                    f"/api/v1/sessions/{_SESSION_ID}/roster/{_ENTRY_ID}/verify",
                    headers=headers,
                )
                assert resp.status_code == 200, resp.text
                assert resp.json()["payment_status"] == "verified_paid"

                # 5. Complete session (no shuttles)
                resp = client.post(
                    f"/api/v1/sessions/{_SESSION_ID}/complete",
                    json=[],
                    headers=headers,
                )
                assert resp.status_code == 200, resp.text
                assert resp.json()["status"] == "completed"

                # 6. Fetch P&L
                resp = client.get(f"/api/v1/sessions/{_SESSION_ID}/pnl", headers=headers)
                assert resp.status_code == 200, resp.text
                pnl = resp.json()

                # 1 external verified_paid × $10 = $10 income
                # Court slot 09:00–11:00 × $15/hr = $30 court cost
                # net = $10 - $30 = -$20
                assert pnl["total_fees_collected"] == 10.0
                assert pnl["court_cost"] == 30.0
                assert pnl["shuttle_cost"] == 0.0
                assert pnl["net"] == -20.0
                assert pnl["external_paid_count"] == 1
                assert len(pnl["booker_breakdown"]) == 1
                assert pnl["booker_breakdown"][0]["amount"] == 30.0
    finally:
        app.dependency_overrides.clear()
